### ISSUE TITLE
Help Getting this to work

### ISSUE THREAD

**Issue by zakkwylde** [Trekky12/kburns-slideshow#1]
Hi, very interested in your project, but I am having trouble running it with the example.json.
How do you pass it via cmd line?

Could you document and add a fully working example with the data to the codebase. Just images would be fine.

Thanks

**Comment by Trekky12** [comment]
Hey so this project is currently work in progress and still improving.

So you could either set the parameters by command line or with a config file (```example.json```)

For the CLI parameters you only need to define the output file (```out.mp4```) and some inputs (```-i <filenames>```:
```python main.py out.mp4 -i data/1.jpg data/2.jpg data/1.mp4 data/3.jpg```

All the other possible parameters are visible when calling the program without parameters (```python main.py```) or by looking in ```slideshow/cli.py```.

With a config file you have the ability to define some parameters only for specific slides (e.g. a overlay text, a subtitle text, a specific transition, a slide duration, a fade duration, ...).
You can use the config file like that:
```python main.py out.mp4 -f example.json```

There are currently still some bugs and some features missing, but I'll document the project when these things are ready in more detail.

So in the meantime feel free to ask, if something is not working.

**Comment by Trekky12** [comment]
You can find the documentation in the README
