### ISSUE TITLE
I can't add audio file version 1.5 windows EXE

### ISSUE THREAD

**Issue by tqctqc1** [Trekky12/kburns-slideshow#15]
hello, please help me how to add mp3 audio file (Windows exe version. I can add photos and export mp4 files, but don't know how to add mp3. thank you.

**Comment by tqctqc1** [comment]
thanks for the reply

Here is the log, I have the audio file using "add Audio" Button, but audio
has not been added, Is the problem caused by aubio windows 64?




Vào 00:43, T.6, 9 Th12, 2022 Trekky12 ***@***.***> đã viết:

**Comment by Trekky12** [comment]
Actually there is no logfile attached. 
Aubio is used when the music is synced but it should be possible to add music without aubio at All. So I think aubio is not the problem.
