### ISSUE TITLE
Creation of temporary files ffmpeg is hardcoded to fixed commandline (ultrafast etc.)

### ISSUE THREAD

**Issue by jedcooper** [Trekky12/kburns-slideshow#16]
As title. So the general settings for ffmpeg commandline is obsolete. As I don't think it's intentionally I file this as an issue.
For example I'm using: `"output_parameters": "-preset p7 -tune hq -profile:v high -multipass qres -rc vbr -cq 16 -qmin 16 -qmax 16 -b:v 0k",` along with `"output_codec": "h264_nvenc",`
which is working fine working without temporary files for 3-4 pictures. 
But with a bigger pictures count it soon gets out of memory (log shows FFMPEG cancel) so using temporary files gets mandatory and - as said - user's custom ffmpeg quality commandline obsolete, unfortunately.

In slideshow/Queue.py: [snippet.txt](https://github.com/Trekky12/kburns-slideshow/files/12584706/snippet.txt)

**Comment by Trekky12** [comment]
Could you please explain this in more detail? Indeed the ffmpeg command needs high ressources without temporary files. So for many slides it is recommended to use the temporary files option.

**Comment by jedcooper** [comment]
Hello, first thank you for your effort making this software! Appreciated!  :D

Encoding with user setting be it speed or quality, for the last it makes no sense to have the temporary files spedup, they are then worse in quality and concatenated in good quality which can't be in good quality anymore, because the source (temp files) are of "fast/quick quality" and not the user set quality.

The source has to be same or better quality than target. This is not the case with your hardcoded "-preset ultrafast", default bitrate etc. for temporary files, if the user wants more quality than "ultrafast" and default bitrate.

I don't know how to link code from Queue.py here. Therefore I put a snippet.txt in OP.

What else do you need to know in detail?

**Comment by Trekky12** [comment]
You are right, I will look into it and maybe add a new setting field for the temporary files creation.

Feel free to add a PR for this feature.

**Comment by Trekky12** [comment]
@jedcooper Could you please try the lastest source from the development branch?

**Comment by Trekky12** [comment]
@jedcooper Could you please test the source from the latest development branch?
