### ISSUE TITLE
Subtitles and Slides sync option

### ISSUE THREAD

**Issue by pk1130** [Trekky12/kburns-slideshow#6]
@Trekky12 Hi! I am using the cli version of this app as back-end for my use case. I see there is an option to explicitly sync videos and background music, but there seems to be no such option to explicitly sync slides with their corresponding titles/subtitles. Is there a way I can ensure that if slide 1 runs for 5 seconds, then its corresponding title also run for 5 seconds?

Thanks for making such a useful app/repository!

**Comment by Trekky12** [comment]
Thank you for the kind message 😊 

Actually the subtitles should always start at the end of the transition-in:
https://github.com/Trekky12/kburns-slideshow/blob/5883ab585ad08ec4ef020cb131d70a43cbc671ed/slideshow/SlideManager.py#L854-L855
 and end on the end of the transition-out:
https://github.com/Trekky12/kburns-slideshow/blob/5883ab585ad08ec4ef020cb131d70a43cbc671ed/slideshow/SlideManager.py#L858-L859

With titles you mean the black overlay title like in the demo ("Demo Slideshow"), right?
![image](https://raw.githubusercontent.com/Trekky12/kburns-slideshow/master/docs/demo/demo.gif)

At the moment it is indeed not possible to sync the titles duration to the slides duration. Do you want to sync all titles to the corresponding slide durations?

**Comment by Trekky12** [comment]
Hey @pk1130, 
I've added a cli parameter `--sync-titles-to-slides` in the development branch. Is this what you need?

**Comment by Trekky12** [comment]
@pk1130 can this issue be closed?
