### ISSUE TITLE
How Can I Use Zoom and Pan Effects in Python Code

### ISSUE THREAD

**Issue by thisisashukla** [Trekky12/kburns-slideshow#7]
Hi @Trekky12 

Thanks for this awesome repository. I am working on a project where i need to implement custom zoom and pan effects on images and stitch them up together to make a video.

I have to implement pan and zoom effects with custom areas in images to be zoomed and panned. There are focus areas in every image i want the zoom and pan effects to highlight. 

I am not good with shell scripting or FFMPEG, but i have working knowledge of Python. Any help on how can i implement custom zoom and pan effects on a set of images using only Python would be really appreciated. 

**It would be a great help if you can spare some time to guide me on implementing KBurns effects on images using Python. Thanks**

**Comment by Trekky12** [comment]
Hey @thisisashukla, 

this project is using FFMPeg filters to create the zoom-pan effects. The underlying logic is based on the awesome blogpost https://el-tramo.be/blog/ken-burns-ffmpeg/ of @remko. The blogpost explains the filter chains of FFMPeg in detail. 

Unfortunately I can't assist you in creating these effects without FFMPeg and with only python.

With this project it is not possible to use other zoom-pan effects than the available ones. But I think the software "PhotoFilmStrip" (https://www.photofilmstrip.org/en/) has another approach for these kind of effects. Maybe you can look into this.

**Comment by thisisashukla** [comment]
Thanks for your quick response @Trekky12 i'll check the blog. I am trying to generate these effects programmatically so the software is not of much use to me I believe. 

Thanks again.

**Comment by Trekky12** [comment]
@thisisashukla can this issue be closed?

**Comment by thisisashukla** [comment]
Ye sure @Trekky12
