### ISSUE TITLE
Cannot import name 'ImageTk' from 'PIL'

### ISSUE THREAD

**Issue by cb2-dd** [Trekky12/kburns-slideshow#8]
On a Ubuntu 20.10 and following the instructions I receive the following error:

python3 kbvs.py
Traceback (most recent call last):
  File "kbvs.py", line 1, in <module>
    from gui.app import App
  File "~/Downloads/kburns-slideshow-master/gui/app.py", line 12, in <module>
    from PIL import Image, ImageTk, ImageDraw
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by Trekky12** [comment]
Hey @cb2-dd, 

apparently you need additional packages. Please try to install the package 
```
python3-pil.imagetk
``` 

I fixed the installation instructions 👍
